### ISSUE TITLE
Cannot search, always get an error

### ISSUE THREAD

**Issue by maciossek** [citelao/Spotify-for-Alfred#101]
Hey, thanks for developing the workflow. I cannot search, although I don't use the search feature that often, but I thought I'll let you know something went wrong:

```
# Error Log # 
## Error Info ## 
Invalid argument supplied for foreach()
Line 115, /Users/yolo/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.287B2B45-898D-43F2-8296-8030B3BE6AD0/src/citelao/Spotifious/Menus/Search.php
```

Here is the full log: https://www.dropbox.com/s/kcuji1x5qph41ac/2017-07-31%2002-07-35%20Spotifious.log?dl=0

**Comment by citelao** [comment]
I'll take a look!

You should delete the log now since it has your API secret in it.

**Comment by citelao** [comment]
One of your playlists has a backslash in it (`\`: `lofi hip hop beats [lo-fi hip hop] Chillhop Music .. Chilledcow`) and it's breaking my parser :)

I'll write up a fix but in the meantime you can work around this by removing that playlist from your library (yeah, not really a workaround, but that's the best I have rn).

**Comment by maciossek** [comment]
Many thanks for the quick reply. I'll wait then ^^
