### ISSUE TITLE
Search & Find the Song ✅  Launch the song ❌

### ISSUE THREAD

**Issue by MarcRF** [citelao/Spotify-for-Alfred#106]
Hello and thank you for this workkflow which looks amazing  🙂

I installed everything and am able to look for spotify from alfred search bar 

However, the song doesn't launch, is spotifious still working on Sierra 10.12.6  ?

Have a nice day !  

Marc

**Comment by citelao** [comment]
Thanks!

Song launch works for me. What is happening?

**Comment by MarcRF** [comment]
Hello Citelao 🙂

Thank you for your quick answer 👍

Sorry for the delay, I didn't know how to describe more effectively the issue. Maybe with an exemple ❓
I am able to look for spotify Results from alfred search bar  but then it doesn't launch...

![c-7f6f8464-b0e2-496c-8769-c9e29747f1de](https://user-images.githubusercontent.com/13728395/30106754-cdbb2b82-92fc-11e7-942a-abad7a40e574.png)

![c-acee047a-fa0e-480e-98c2-52ec11e3ad41](https://user-images.githubusercontent.com/13728395/30106796-ec58afa6-92fc-11e7-92bb-57cecda7f451.png)

Have a nice day !  ☀️ 

Marc

**Comment by citelao** [comment]
That's weird... a couple people are reporting this issue, but I cannot reproduce it myself.

Playing from search works for me, as does launching from an album.

Can you give me some more information? Which version of Spotify and Alfred do you have?

**Comment by MarcRF** [comment]
Thanks for your message 👍
👌  I feel so stupid I hadn't install spotify app 'cause I thought it was searching on it online: you might add install spotify app in the read.me :)

**Comment by citelao** [comment]
That's helpful! I'll think about adding it to the README like you suggested :) Glad you got it working.
