### ISSUE TITLE
Selecting a track doesn't play

### ISSUE THREAD

**Issue by bwobst** [citelao/Spotify-for-Alfred#110]
* spotifious 0.13.4
* Alfred 3.5.1, Build 883
* macOS High Sierra
 
Connected spotifious to Spotify and am able to populate the dropdown with tracks, artists, playlists, etc. Not able to play a selected track.

Tried:
* Clicking tracks with the mouse
* Selecting them with the appropriate keyboard shortcut (e.g. cmd+5)
* Hitting RETURN/ENTER
* The above three things on a different machine running macOS High Sierra

Am I missing something obvious here?

**Comment by citelao** [comment]
Which version of Spotify do you have installed on your computer?

**Comment by bwobst** [comment]
None. Just needed to download the client.

**Comment by citelao** [comment]
I'm glad you figured it out! I definitely should clarify that.
