### ISSUE TITLE
Issue with search

### ISSUE THREAD

**Issue by ergelo** [citelao/Spotify-for-Alfred#116]
Hey, I'm having issues searching within Spotifious. whatever I try to type or if I select the artist or album of the current song, I get an error. I'm attaching an example log - any help in trying to solve the issue would be appreciated! Thanks! 

[com.citelao.spotifious2018-02-23 06-02-37 Spotifious.log](https://github.com/citelao/Spotify-for-Alfred/files/1753461/com.citelao.spotifious2018-02-23.06-02-37.Spotifious.log)

**Comment by citelao** [comment]
Can you go to the settings menu (launch Spotifious, type `s`, and then select `Login again to my Spotify application`?).

You're getting an error 401 not authorized, which might be a bug with your credentials.

**Comment by citelao** [comment]
Closing since we were never able to diagnose this.
