### ISSUE TITLE
Error when opening playlist; "Undefined offset: 1"

### ISSUE THREAD

**Issue by itsaphel** [citelao/Spotify-for-Alfred#122]
Getting this error when I try to open any playlist. Songs seem to work fine, as do albums.

Here's a relevant snippet from the error log:

```
# Error Log # 
## Error Info ## 
Undefined offset: 1
Line 16, /path/to/Alfred/Alfred.alfredpreferences/workflows/user.workflow.x/src/citelao/Spotifious/Menus/Detail.php

## Symbols ## 
Array
(
    [options] => Array
        (
            [depth] => 2
            [URIs] => Array
                (
                )

            [args] => Array
                (
                    [0] => spotify:playlist:37i9dQZF1DWXLeA8Omikj7
                    [1] => brain food
                )

            [search] => 
            [query] => spotify:playlist:37i9dQZF1DWXLeA8Omikj7 ⟩ brain food ⟩
        )
```

Seems to be fired at https://github.com/citelao/Spotify-for-Alfred/blob/master/src/citelao/Spotifious/Menus/Detail.php#L16 - contents of URIs there don't seem to match up with what the code is expecting.

Running v0.13.7 (https://github.com/citelao/Spotify-for-Alfred/releases/tag/v0.13.7)

**Comment by citelao** [comment]
I'm getting the same issue, too. I'll take a look.

Thanks for reporting this!

**Comment by citelao** [comment]
Looks like Spotify took the `user:` part out of it's playlist URLs:

[`is_spotify_uri`](https://github.com/citelao/Spotify-for-Alfred/blob/master/src/citelao/Spotifious/Spotifious.php#L337) is outdated.

Should probably read:

```
$regex = '/^(spotify:(?:album|artist|track|(?:user:[^:]+)?:playlist):[a-zA-Z0-9]+)$/x';
```
instead of
```
$regex = '/^(spotify:(?:album|artist|track|user:[^:]+:playlist):[a-zA-Z0-9]+)$/x';
```

**Comment by citelao** [comment]
I've just pushed 0.13.8, which fixes the issue! Thanks for reporting!
