### ISSUE TITLE
Cannot set country code

### ISSUE THREAD

**Issue by mikemartin** [citelao/Spotify-for-Alfred#124]
Latest Release v0.13.7: Make it work again
Alfred v3.8.1 [961]
MacOS 10.14.5

When going through the setup process I receive an error when entering my country code. I've tried AU, AUS, US, etc. 

`Could not access https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json.`

<img width="605" alt="Screen Shot 2019-05-27 at 11 25 14 am" src="https://user-images.githubusercontent.com/414211/58389988-2a8cac00-8072-11e9-8166-c5f8d74a2ffb.png">

Full error log:

```
# Error Log # 
## Error Info ## 
Could not access https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json. Try searching again
Line 25, /Users/mike/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.xxx-xxx-xxx-xxx-xxx/src/citelao/OhAlfred/HTTP/Fetcher.php

## Symbols ## 
Array
(
    [message] => Could not access https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json. Try searching again
    [vars] => Array
        (
        )

    [0] => Array
        (
            [file] => /Users/mike/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.xxx-xxx-xxx-xxx-xxx/src/citelao/OhAlfred/HTTP/JsonFetcher.php
            [line] => 18
            [function] => run
            [class] => OhAlfred\HTTP\Fetcher
            [type] => ->
            [args] => Array
                (
                )

        )

    [1] => Array
        (
            [file] => /Users/mike/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.xxx-xxx-xxx-xxx-xxx/src/citelao/Spotifious/Menus/SetupCountryCode.php
            [line] => 16
            [function] => run
            [class] => OhAlfred\HTTP\JsonFetcher
            [type] => ->
            [args] => Array
                (
                )

        )

    [2] => Array
        (
            [file] => /Users/mike/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.xxx-xxx-xxx-xxx-xxx/src/citelao/Spotifious/Spotifious.php
            [line] => 80
            [function] => __construct
            [class] => Spotifious\Menus\SetupCountryCode
            [type] => ->
            [args] => Array
                (
                    [0] => Country Code ⟩
                )

        )

    [3] => Array
        (
            [file] => /Users/mike/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.xxx-xxx-xxx-xxx-xxx/main.php
            [line] => 24
            [function] => run
            [class] => Spotifious\Spotifious
            [type] => ->
            [args] => Array
                (
                    [0] => Country Code ⟩
                )

        )

)
```

**Comment by citelao** [comment]
Hey @mikemartin!

Does [the URL](https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.json) load in the browser if you click it?

Also, does it work now?

I don't see any HTTP errors in the trace you sent, so I'm hoping it's a transient/larger thing.

**Comment by mikemartin** [comment]
Thanks Ben. Yes, the URL loads in the browser and I can ping the domain.

Mike Martin
mike-martin.ca | @mikemartin604 | +61 413 780 407

________________________________

**Comment by citelao** [comment]
Ok! Well, the easy solution is out the window then :).

Can you double-check that the country code section is still failing? I am not able to reproduce this issue on my box.

Thanks!

— Ben (ben@stolovitz.com)

________________________________

**Comment by mikemartin** [comment]
Hey @citelao! Thanks for looking into this. It finally worked when I checked just now. I wonder if it had something to do with the network at my office.

**Comment by citelao** [comment]
I’m glad you fixed it! Thanks for reporting.

________________________________
