### ISSUE TITLE
[not an issue, but a question] Implementation of Alarm with Spotifious

### ISSUE THREAD

**Issue by SebastianBehrens** [citelao/Spotify-for-Alfred#131]
Love your workflow. I wonder whether it's possible to implement a feature where you set the time and the song/playlist, such that you get woken up by your favourite song. 
(I guess it'd be best if that would work, while computer is in sleep... [not sure if that's possible, but would be necessary imo].)

Thank you for having created Spotifious!

**Comment by citelao** [comment]
Hi @SebastianBehrens!

I'm glad you find my workflow helpful!

I built it primarily to scratch an itch of mine, and I try to direct the little time I have to work on it towards features where I know exactly what I want and how to build it.

In this case, I'm not sure this is a feature I would be able to use myself (I keep my computer outside my bedroom, for example). There's also a number of technical hurdles to work through, for example:

* building a service that lives outside of Alfred to handle executing the alarm.
* ensuring that service can wake devices from sleep.
* building an intuitive UX in Alfred to control the service.

It might even be more straightforward to build a separate app for this feature!

That being said, I welcome contribution; if you or anyone else can find a way to integrate such a feature with Spotifious in an intuitive way, I would be more than happy to help commit the PR.

I do think such functionality would make sense as a separate app. If this is something you'd like to pursue, please feel free to reach out here; I am happy to share the (meager?) resources I have.

Once again, it's nice to hear that you enjoy my work, and thank you for your suggestion! Happy coding.
