### ISSUE TITLE
Current song info

### ISSUE THREAD

**Issue by jvataja** [citelao/Spotify-for-Alfred#135]
The client can't retrieve the information of song playing currently, says 'no track playing'. On Alfred 4.0.9 [1144], MacOS 10.14.6.

**Comment by jvataja** [comment]
My Alfred can't find the Spotify desktop app, so maybe the AppleScript breaks as well?

**Comment by citelao** [comment]
What happens in the AppleScript "Script Editor" app when you run this?

```
tell application "Spotify"
	name of current track
end tell
```

It should output the current song at the bottom.

**Comment by jvataja** [comment]
It almost always returns an empty string. However, sometimes it's working how it should and I can't figure out why. The script returned correct info before Alfred/Spotify-for-Alfred. Is there any fallback to use Spotify API to get song info?

**Comment by citelao** [comment]
I haven't implemented anything that calls out to the Spotify API, but I think it might be possible. You may need a Premium account to do it. I worry that API calls will be too slow for general use, though.

If you restart your computer and don't use Spotifious (but open the Spotify app), do you reliably get a result?

**Comment by fusion2004** [comment]
I'm seeing the same thing as well, and similarly running that script in the script editor is returning a blank string.

**Comment by citelao** [comment]
What version of Spotify are you running? (`Spotify`> `About Spotify`).

I'm running `1.1.26.501.gbe11e53b`, and the script works correctly for me with no issues.

**Comment by citelao** [comment]
Updating to `1.1.33.569.gced9e0f5` and the script fails.

However, this provides output:

```
tell application "Spotify"
	id of current track
end tell
```

Is this the same for you? Looks like Spotify doesn't give out the name anymore (ugh).

**Comment by citelao** [comment]
Seems to be working on newer versions of Spotify, like `1.1.48.625.g1c87c7f7-a`.
