### ISSUE TITLE
Replace terminal-notifier with alerter

### ISSUE THREAD

**Issue by okuramasafumi** [citelao/Spotify-for-Alfred#136]
https://github.com/citelao/Spotify-for-Alfred/blob/master/src/citelao/OhAlfred/OhAlfred.php#L346
Here we use `terminal-notifier`, but it doesn't work on macOS Catalina.

There is a similar tool caller alerter. https://github.com/vjeantet/alerter
I wonder if we can make notification work on Catalina with alerter.

**Comment by tjwds** [comment]
I'm running macOS Catalina and `terminal-notifier` works just fine — what issue are you experiencing?

**Comment by okuramasafumi** [comment]
<img width="415" alt="スクリーンショット 2020-09-09 2 21 41" src="https://user-images.githubusercontent.com/1012014/92508241-3e4a2a80-f243-11ea-9cd2-3994c574ecfa.png">

This showed up when I reinstall Spotifious and play the music. It says "You cannot open terminal-notifier because we cannot verify the developer".

**Comment by tjwds** [comment]
@okuramasafumi I was able to bypass this restriction by going to Settings > Security & Privacy and clicking the "allow" button under "General".

**Comment by okuramasafumi** [comment]
Ah I didn't know it shows here and we can enable it manually, thank you!
