### ISSUE TITLE
Playlist search

### ISSUE THREAD

**Issue by citelao** [citelao/Spotify-for-Alfred#21]
[Websockets and magic?](http://www.alfredforum.com/topic/1644-spotifious-a-natural-spotify-controller-for-alfred/?p=19826)
- Faye pubsub?
- Potential for app speed increase?

Failing that: Open playlist URLs in Spotify.

**Comment by russmatney** [comment]
+1 would love playlist search/control

**Comment by citelao** [comment]
This has been in Spotifious since March 😁
