### ISSUE TITLE
Remote integration

### ISSUE THREAD

**Issue by matejkramny** [citelao/Spotify-for-Alfred#52]
I would love to be able to use this with Alfred Remote..

Its saying 'no workflows currently contain remote pages'. Not sure if this is Alfred's fault or if this plugin needs to enable some setting..

Any ideas on how to do that?

![screenshot 2015-01-28 19 01 43](https://cloud.githubusercontent.com/assets/797608/5944608/3c202206-a720-11e4-9faa-019b2de3dc1e.png)

**Comment by citelao** [comment]
I learned about Alfred Remote's API at about noon yesterday!

I'll get an update out in the next few days :fearful:
