### ISSUE TITLE
Use SpotifyBeta if it is open, instead of Spotify

### ISSUE THREAD

**Issue by chris5marsh** [citelao/Spotify-for-Alfred#55]
I've just started using [SpotifyBeta](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Welcome-to-the-Desktop-Beta/td-p/932803), mostly because of the excellent remote control capability.

However, Spotifious opens Spotify by default so doesn't control SpotifyBeta. Is it trivial to update the workflow to check if SpotifyBeta is installed, or open, or to update it in the settings?

**Comment by citelao** [comment]
It would be a trivial change, but the Spotify beta doesn't have applescript hooks.

**Comment by chris5marsh** [comment]
Fair enough. Thanks for the quick response!
