### ISSUE TITLE
Currently Playing view broken after latest Spotify update

### ISSUE THREAD

**Issue by ghost** [citelao/Spotify-for-Alfred#56]
Spotify updated for me today, and afterwards the currently playing view reports that nothing is playing. Searching still works, though.

Here's the log output from php -f main.php -- "{query}" | tee ~/Desktop/Spotifious.log:
```
<?xml version='1.0'?>
<items>

	<item uid='1425553424-No track playing' valid='yes' autocomplete=''>
		<arg>playpause⟩</arg>
		<title>No track playing</title>
		<subtitle></subtitle>
		<icon>include/images/playing.png</icon>
		<text type='copy'></text>
	</item>


	<item uid='1425553424-No album' valid='no' autocomplete=''>
		<arg>null</arg>
		<title>No album</title>
		<subtitle></subtitle>
		<icon>include/images/album.png</icon>
		<text type='copy'></text>
	</item>


	<item uid='1425553424-No artist' valid='no' autocomplete=''>
		<arg>null</arg>
		<title>No artist</title>
		<subtitle></subtitle>
		<icon>include/images/artist.png</icon>
		<text type='copy'></text>
	</item>


	<item uid='1425553424-Search for music...' valid='no' autocomplete=''>
		<arg>null</arg>
		<title>Search for music...</title>
		<subtitle>Begin typing to search</subtitle>
		<icon>include/images/search.png</icon>
	</item>
</items>
```

The Alfred workflow debug mode has the following error in the log too:
```
[STDERR: alfred.workflow.input.scriptfilter] 50:55: syntax error: Expected end of line but found identifier. (-2741)
```

**Comment by vdesabou** [comment]
FYI, I have same problem with my workflow so here are my findings on this topic. 

See issue https://github.com/vdesabou/alfred-spotify-mini-player/issues/66 
I've found a workaround (see comment here https://github.com/vdesabou/alfred-spotify-mini-player/issues/66#issuecomment-76948421) but it is still not working for main action, which is `play track`
I've raised the problem to Spotify already.

The only thing for now is to prevent auto-update of Spotify to 1.0.1.x, see https://github.com/vdesabou/alfred-spotify-mini-player/issues/66#issuecomment-76964100

**Comment by citelao** [comment]
Ew, I thought it might be something like that. I was gonna ping you. 







​Is there a Spotify support thread about this?



On Thursday, Mar 5, 2015 at 5:13 AM, Vincent <notifications@github.com>, wrote:

FYI, I have same problem with my workflow so here are my findings on this topic. 


See issue vdesabou/alfred-spotify-mini-player#66 

I've found a workaround (see comment here vdesabou/alfred-spotify-mini-player#66 (comment)) but it is still not working for main action, which is play track

I've raised the problem to Spotify already.


The only thing for now is to prevent auto-update of Spotify to 1.0.1.x, see vdesabou/alfred-spotify-mini-player#66 (comment)

**Comment by vdesabou** [comment]
>​Is there a Spotify support thread about this?

There is [this community thread](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434) and this [tweet](https://twitter.com/SpotifyCares/status/573246522814554113). But I'm not sure someone from Spotify really takes care of it.

**Comment by zachfeldman** [comment]
Any ideas on this guys @citelao perhaps? This renders the plugin completely useless for me, I can search tracks but not play them...

**Comment by citelao** [comment]
I wish I could help. I'm honestly considering scrapping development unless spotify changes something because, like you said, I need this AppleScript for the plugin to work. 






On Thursday, Mar 19, 2015 at 10:55 AM, Zach Feldman <notifications@github.com>, wrote:

Any ideas on this guys @citelao perhaps? This renders the plugin completely useless for me, I can search tracks but not play them...

**Comment by zachfeldman** [comment]
=/ super sad!

-- 
Zach Feldman
908.397.8489
zfeldman.com

I'm writing a book!
http://linuxforhobbyists.com

**Comment by citelao** [comment]
Let's just hope Spotify fixes it :game_die:

**Comment by vdesabou** [comment]
>Let's just hope Spotify fixes it

A Spotify developer is saying [here](http://stackoverflow.com/questions/29039514/applescript-to-tell-spotify-to-play-isnt-working-after-osx-update-to-yosemite/29047174#29047174) that it has been fixed and the update is rolling out (will take one or two weeks to reach end users).
I updated my [blog article](http://alfred-spotify-mini-player.com/blog/issue-with-latest-spotify-update/) with this info

**Comment by bobintornado** [comment]
super sad. Can't wait. :/

**Comment by citelao** [comment]
Should be fixed now :)
