### ISSUE TITLE
Search results displaying fallback square

### ISSUE THREAD

**Issue by weiweihuanghuang** [citelao/Spotify-for-Alfred#57]
![screen shot 2015-03-17 at 3 21 38 pm](https://cloud.githubusercontent.com/assets/1271897/6689280/755eff2e-ccb9-11e4-8a9f-039a9abf23f7.png)

**Comment by citelao** [comment]
I'm not sure what the issue is here. 







​Are you talking about the [][][][][]-----?

**Comment by weiweihuanghuang** [comment]
yes

**Comment by citelao** [comment]
Oh, that's just the confusing way I output popularity. It used to be different thickness Unicode chars.

I'll change it if Spotify ever fixes their applescript bug; otherwise any further development isn't really worth it.

**Comment by weiweihuanghuang** [comment]
Ah I see, no problem then!
