### ISSUE TITLE
Playing track not detected, chosen song not playing

### ISSUE THREAD

**Issue by akmur** [citelao/Spotify-for-Alfred#58]
What could I be possibly do wrong? I'm on latest Yosemite, with most up-to-date Alfred, Spotify-for-Alfred and Spotify.
Thanks a bunch!

**Comment by akmur** [comment]
Issue was caused by latest Spotify. Downgraded, it works

**Comment by citelao** [comment]
Glad you fixed it! I'm hoping Spotify adds support back soon.
