### ISSUE TITLE
Unicode symbols are not passed to spotify correctly

### ISSUE THREAD

**Issue by romcheg** [citelao/Spotify-for-Alfred#59]
How to reproduce:

 - Open
 - Type in or paste Океан Ельзи
 - Select "Search for Океан Ельзи" in the menu

Result: Spotify opens a search page for a strange string.

![2015-04-07 17 16 41](https://cloud.githubusercontent.com/assets/214072/7026428/e24eb444-dd49-11e4-91e0-6352bdca0662.png)

**Comment by citelao** [comment]
Yikes!

Unicode errors... :anger: 

I'll spend some time fixing it.

**Comment by romcheg** [comment]
@citelao I'd post a patch but I know nothing about how PHP works, sorry.

**Comment by citelao** [comment]
Unfortunately, this error isn't on my end. It's Spotify's— try running `tell application "Spotify" to open location "spotify:search:Океан Ельзи"` in Script Editor.

I'll do a little more poking around, but I don't think I can fix this.

**Comment by citelao** [comment]
It doesn't seem at all fixable given Spotify's present state :/
