### ISSUE TITLE
When changing to prev/next track, notifications show currently playing track

### ISSUE THREAD

**Issue by GaryKing** [citelao/Spotify-for-Alfred#61]
If I go to the prev/next track, the notification shown shows the track that was playing before the track change, rather than the new one.

**Comment by scotje** [comment]
A quick fix for this is to insert a 0.1 second delay into the AppleScript that gets run when changing tracks.

So change this line: https://github.com/citelao/Spotify-for-Alfred/blob/master/src/citelao/Spotifious/Spotifious.php#L190

from this:
```php
$as = new ApplicationApplescript("Spotify", $query . " \n return name of current track & \"✂\" & album of current track & \"✂\" & artist of current track & \"✂\" & spotify url of current track & \"✂\" & player state");
```

to this:

```php
$as = new ApplicationApplescript("Spotify", $query . " \n delay 0.1\n return name of current track & \"✂\" & album of current track & \"✂\" & artist of current track & \"✂\" & spotify url of current track & \"✂\" & player state");
```

To find the PHP file, open the Spotifious workflow, double click on the "Run Script" element, click "Open workflow folder" in the bottom right, and then browse to "src/citelao/Spotifious" in that folder and open Spotifious.php.
