### ISSUE TITLE
Stuck "Verifying your information..."

### ISSUE THREAD

**Issue by veenified** [citelao/Spotify-for-Alfred#71]
After adding the Client ID and Client Secret, I clicked "Save" and a message displays saying "Verifying your information..."
![screen shot 2016-02-22 at 3 44 39 pm](https://cloud.githubusercontent.com/assets/13979/13232090/a7ef63c8-d97b-11e5-87ac-69eda44d21e8.png)
...and after waiting for over 5 minutes, nothing happens. Attempting to refresh the page or revisit via Ctrl+Cmd+Return displays a blank page with the webpage attempting to load. I added debug logging and I only see the following line entry in the log file:
`(php -S localhost:11114 & open 'http://localhost:11114/include/setup/index.php' && sleep 600; kill -9 $!) > /dev/null 2>/dev/null &`

**Comment by veenified** [comment]
Resolved. Found Little Snitch was blocking the connection attempts and wasn't bringing the prompt to the foreground. Added a rule to accept those connections and everything works like a charm now.

**Comment by citelao** [comment]
Glad you fixed it!
