### ISSUE TITLE
Add disabling iTunes miniplayer in Installation guide

### ISSUE THREAD

**Issue by technicalpickles** [citelao/Spotify-for-Alfred#74]
I was trying to do this step: 

> Click the text field labeled Hotkey and press ^⌘⏎.

And this kept coming up:

![image](https://cloud.githubusercontent.com/assets/159/15251040/9a4c1036-18f5-11e6-84c5-2e85e2a4077a.png)

It took me a few minutes to track it down to the iTunes Miniplayer. To disable, go to Features -> iTunes then click in the short cut. Press delete to remove it.

**Comment by citelao** [comment]
To be clear, was iTunes miniplayer bond to `alt+command+enter` or `control+command+enter`?

It might just have been a problem with my wording.

**Comment by technicalpickles** [comment]
It was bound to control-command-enter, i.e. what the documentation said to set for the hot key.

**Comment by citelao** [comment]
That's odd... I remember picking the hotkey to be separate.

No matter, I'll change the tutorial to prefer "alt." Thanks!

**Comment by technicalpickles** [comment]
From my reading, it sounds like there's supposed to be parity with the iTunes mini player. If that's the case, it makes sense to have one option being to replace the keybinding. I only use Spotify, no iTunes, so that makes sense for me at least.

**Comment by citelao** [comment]
Fixed! Thanks :)

I'm actually a fan of having both up at the same time, but I don't remember the default setting for the mini player, so I'm just gonna leave the example hotkey as is.

**Comment by technicalpickles** [comment]
Thanks!
