### ISSUE TITLE
Alfred 3 compatibility

### ISSUE THREAD

**Issue by BartVB** [citelao/Spotify-for-Alfred#75]
I got a 'mkdir() failed' error when I installed Spotifious. This was easily fixed by modifying src/citelao/OhAlfred/OhAlfred.php . I just changed '2' into '3' for cache and storage.

A real solution would figure out the currently installed version of Alfred to determine the appropriate paths.

Apart from that Spotifious seems to work flawlessly with Alfred 3. Nice work!

**Comment by citelao** [comment]
Thank you!

I have been out of the country and so unable to work on the plugin (Spotify roaming 😢) but I'll try to make the changes as quick as possible.

**Comment by JessicaSachs** [comment]
@BartVB solution is working for me :)

**Comment by johnathanz** [comment]
Thanks @BartVB. Solution works :D 

For anyone reading this. Change the setting within the `Alfred 3 / workflows/` folder
