### ISSUE TITLE
Spotifious not responding

### ISSUE THREAD

**Issue by Benjamski** [citelao/Spotify-for-Alfred#76]
I love this workflow and it normally works great, but I've had a lot of issues with it being non-responsive.

For instance, when I first open it, usually by playing a playlist, nothing happens and I have to repeat the step a second time to get a response. Sometimes that never works and I need to open Spotify first before it will work.

Anyone else having these issues?

**Comment by citelao** [comment]
Are you starting the playlist through the plugin? If so you might be using Spotify Mini Player, not Spotifious.

I have been unable to verify anything for the past weeks because I am in a different country with no Spotify service :(

**Comment by Benjamski** [comment]
Ah! I actually have both enabled so that's my first problem. But it turns out both aren't really working for me after the Alfred3 update so I might have to go without them for a while.

**Comment by citelao** [comment]
You might want to check out #75 

Spotify Mini Player and Spotifious don't conflict :)

**Comment by Benjamski** [comment]
I think actually the conflict wasn't between the workflows, it was in me not realizing which one I was using when :p

**Comment by citelao** [comment]
oh, then, WONTFIX user error 😛

**Comment by Benjamski** [comment]
Well played. ¯\_(ツ)_/¯
