### ISSUE TITLE
Enhancement Request: Support spotify for web

### ISSUE THREAD

**Issue by derkork** [citelao/Spotify-for-Alfred#77]
It would be awesome if this could control the Spotify web app running in the browser as well.

**Comment by citelao** [comment]
Unfortunately, there are no hooks I can tie the plugin to. There's no way I can tell the web player to, say, "pause" or "go to the next track," at least not without hacks.

You might want to search the [Idea Exchange](https://community.spotify.com/t5/Idea-Submissions/idb-p/ideas_submissions) for such functionality (ability to control the web player externally), though I doubt it's possible.
