### ISSUE TITLE
Uninstall workflow

### ISSUE THREAD

**Issue by MichaelMallett** [citelao/Spotify-for-Alfred#79]
Hi, the installation is a little opaque, can you tell me how to remove the packages that were installed with this workflow please?

**Comment by citelao** [comment]
This workflow has no external dependencies :)

You can uninstall it completely by removing `workflows/spotifious` from your `.alfredpreferences` file.

The workflow also caches data in:

- `~/Library/Application Support/Alfred 3/Workflow Data/com.citelao.spotifious/`
- `~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.citelao.spotifious/`

You can remove those folders to uninstall Spotifious completely. This will remove your settings. Sad to see you go, though!

**Comment by MichaelMallett** [comment]
Great thankyou. I will likely be back, I'm just testing a few things out.

Is it possible to add to current spotify queue using this?
