### ISSUE TITLE
  Is it possible to add to current spotify queue using this?

### ISSUE THREAD

**Issue by MichaelMallett** [citelao/Spotify-for-Alfred#80]
I've noticed that most tools that interact with spotify can't add to the queue, is that the same here? Looking to be able to control the office playlist in slack, through alfred

**Comment by citelao** [comment]
The best any app can do using the web API is create and play a playlist. If you can manage the playlist well, you can emulate a queue.

I have not had the time to sit down and perfect that behavior, though that is what I want most for the app (I use it too 😄 )

**Comment by MichaelMallett** [comment]
I know right, everyone wants an add to queue function, seems like the most
useful function and people have been asking spotify for years!

I did find this on Hacker News today that might hold some promise?
http://www.hammerspoon.org

**Comment by citelao** [comment]
UI automation is always such a brittle, solution :P I'll be working on a nice playlist solution though.

**Comment by MichaelMallett** [comment]
Of course, but needs must
