### ISSUE TITLE
Spotify web API authentication requirement changes

### ISSUE THREAD

**Issue by atabbott** [citelao/Spotify-for-Alfred#90]
Spotify updated web API requirements in regards to authentication. These changes were announced [here](https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/) on 17th Jan 2017, effective 29th May 2017 removed the ability for to make any unauthenticated calls to the API. 

Currently searching appears to make unauthenticated calls to the API. A 401 error is returned with the response 'No token provided'. 

Issue appears to stems from use of an old version of @jwilsson 'spotify-web-api-php' wrapper that did not include authentication token with all types of API request. 

A new version of the 'spotify-web-api-php' wrapper should resolve this issue.

**Comment by atabbott** [comment]
I'll start working on a quick fix now I'll submit through a pull request.

**Comment by atabbott** [comment]
Harder fix than initially thought due to architecture of JSON requests for 'DetailArtist' and 'DetailAlbum'

**Comment by atabbott** [comment]
#91 submitted potential fix for evaluation

**Comment by citelao** [comment]
I'll take a look!

**Comment by citelao** [comment]
Fixed in v0.13.3 😁
