### ISSUE TITLE
Can't link a Spotify application

### ISSUE THREAD

**Issue by brycehamrick** [citelao/Spotify-for-Alfred#95]
I set up a new Macbook and can't get Spotifious to work. I can add the workflow, I can set the country code, but the "Link your Spotify application" step doesn't do anything, it doesn't respond at all when I select that option.

**Comment by citelao** [comment]
Can you repeat the install process as best you can using Alfred's debugger and then post the output here?

**Comment by citelao** [comment]
Give it a shot with [the newest version](https://github.com/citelao/Spotify-for-Alfred/releases/tag/v0.13.3.2). I think you might have been experiencing the same bug some other folks saw.

**Comment by citelao** [comment]
I'm gonna close this since I think this issue is fixed. Feel free to reopen if my suggestion didn't fix it!
