### ISSUE TITLE
Small Design issue

### ISSUE THREAD

**Issue by fabi94music** [citelao/Spotify-for-Alfred#99]
Hello, 
discovered that the title and singe icon do have a little white frame around, which the other icons do not have. Nothing serious, but maybe you could fix that :) 

![spotify for alfred_icon](https://user-images.githubusercontent.com/29753374/28693932-6fab10a6-7327-11e7-9661-6c6472fa7d22.png)

PS: there is also an icon for compilation missing.

**Comment by citelao** [comment]
Probably b/c I saved them as PNG-8 instead of PNG-24 if I know myself...

What's a compilation?

**Comment by fabi94music** [comment]
<img width="640" alt="bildschirmfoto 2017-07-29 um 01 20 18" src="https://user-images.githubusercontent.com/29753374/28739571-4a0f01ba-73fc-11e7-896d-e0f90697b053.png">

HI, uploaded a screenshot. A compilation is like a best of or something. There is no "cover" shown.

**Comment by citelao** [comment]
Weird; I'm surprised they even work out of the box.

What's surprising to me is that I don't see it on albums or check notifications, but I *do* see it on tracks and the settings dash.

**Comment by fabi94music** [comment]
Okay, yeah I see it on title, single, notification (unchecked checkbox), the " - " for update playlist cache etc. 
Could you replace them with a higher bit version? :) Would be very nice :) Otherwise your app is absolutely perfect 👍

**Comment by citelao** [comment]
See #100 

If you install [the dev version there](https://github.com/citelao/Spotify-for-Alfred/blob/623dfbb102db997682225147dda026891db725f7/dist/Spotifious.alfredworkflow?raw=true) it should be fixed.

**Comment by fabi94music** [comment]
great thank you ! Solved, accept for that "Compilation" issue, where no cover is displayed at all. Maybe you could just add to show the album cover icon.
